name: Dispatch readme

on:
  repository_dispatch:
    types:
      - dispatch_readme

jobs:
  get_target_branches:
    name: Get target branches
    uses: ./.github/workflows/get_target_branches.yml
    with:
      include_base: true
  generate:
    name: Generate readme
    needs: get_target_branches
    permissions:
      contents: write
    strategy:
      matrix:
        target-branch: ${{ fromJSON(needs.get_target_branches.outputs.target_branches) }}
    uses: Gakuto1112/FiguraAvatarsReadmeTemplate/.github/workflows/generate_my_figura_avatar_readme.yml@main
    with:
      branch-name: ${{ matrix.target-branch }}