name: Generate README

on:
  push:
    branches:
      - '[A-Z]*'
    paths:
      - .github/README_templates/**
      - .github/readme_generator/**
      - .github/workflows/generate_readme.yml

jobs:
  generate-readme:
    name: Generate README
    permissions:
      contents: write
    uses: ./.github/workflows/generate_readme_core.yml
    with:
      branch-name: ${{ github.ref_name }}