name: Generate readme

on:
  push:
    branches:
      - base
      - '[A-Z]*'
    paths:
      - .github/README_templates/**
      - .github/workflows/generate_readme.yml

jobs:
  generate-readme:
    name: Generate readme
    permissions:
      contents: write
    uses: Gakuto1112/FiguraAvatarsReadmeTemplate/.github/workflows/generate_my_figura_avatar_readme.yml@main
    with:
      branch-name: ${{ github.ref_name }}