name: Generate README

on:
  push:
    branches:
      - base
      - Shizuko
      - Izuna
      - Marie
      - Momoi
      - Midori
      - Shiroko
    paths:
      - .github/README_templates/**
      - .github/workflows/generate_readme.yaml

jobs:
  generate-readme:
    name: Generate README
    permissions:
      contents: write
    uses: Gakuto1112/FiguraAvatarsReadmeTemplate/.github/workflows/generate_my_figura_avatar_readme.yaml@main
    with:
      branch-name: ${{ github.ref_name }}