name: Request review

on:
  workflow_run:
    workflows:
      - Trigger request review action
    types:
      - completed

jobs:
  call_workflow:
    name: Call workflow
    permissions:
      pull-requests: write
    uses: Gakuto1112/PublicPullRequestWorkflows/.github/workflows/request_review_core.yml@main
    with:
      reviewer: Gakuto1112